name: Daily README Update

on:
  schedule:
    # Runnning every day at 00:00 UTC
    - cron: '58 9 * * *'
  workflow_dispatch: # allow you running this action manually

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Mandatory, that action can be push to repository

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update README.md
        # Change FIle README.md example at this below can added row text with date.
        run: |
          echo "" >> README.md
          echo "- Update terakhir: $(date)" >> README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'mahardikakdenie'
          git config --global user.email 'kucingemas744@gmail.com'
          
          git add README.md
          
          # Cek apakah ada perubahan sebelum commit, untuk mencegah error
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore: auto-update README per hari [skip ci]" && git push origin main)
